// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: books.sql

package db

import (
	"context"
)

const checkoutBook = `-- name: CheckoutBook :one
UPDATE books SET quantity = quantity - 1 WHERE id = $1 AND quantity > 0 RETURNING id, title, author, quantity
`

func (q *Queries) CheckoutBook(ctx context.Context, id int32) (Book, error) {
	row := q.db.QueryRow(ctx, checkoutBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Quantity,
	)
	return i, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (title, author, quantity) VALUES ($1, $2, $3)
RETURNING id, title, author, quantity
`

type CreateBookParams struct {
	Title    string
	Author   string
	Quantity int32
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook, arg.Title, arg.Author, arg.Quantity)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Quantity,
	)
	return i, err
}

const getBook = `-- name: GetBook :one
SELECT id, title, author, quantity FROM books WHERE id = $1
`

func (q *Queries) GetBook(ctx context.Context, id int32) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Quantity,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author, quantity FROM books
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnBook = `-- name: ReturnBook :one
UPDATE books SET quantity = quantity + 1 WHERE id = $1 RETURNING id, title, author, quantity
`

func (q *Queries) ReturnBook(ctx context.Context, id int32) (Book, error) {
	row := q.db.QueryRow(ctx, returnBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Quantity,
	)
	return i, err
}
